### ISSUE TITLE
how do we disable YouCompleteMe?

### ISSUE THREAD

**Issue by cheoljoo** [wonmin82/dotfiles#6]
@wonmin82   how are you?
how do we disable YouCompleteMe?

- [ ubuntu 14.04 ] : choose no when install the YouCompleteMe
  - run vi
  - YouCompleteMe unavailable: requires Vim 7.4.1578+.
  - Press ENTER or type command to continue

- [ubuntu 18.04]  : choose no when install the YouCompleteMe
  - run vi without any message.

- [ ubuntu 20.04] : build failed - YouCompleteMe
 - run vi without any message.

**Comment by wonmin82** [comment]
You need to install following packages to use YouCompleteMe.

sudo aptitude -y install clang libclang1 libclang-dev cmake mono-complete golang nodejs npm rustc cargo openjdk-11-jdk

Yes.. I know it requires lots of stuff.

There is a line like following in .vimrc

`let s:is_ycm_enabled = 1`

If you set the value of that variable to 0, YouCompleteMe will not be installed.

And for the Ubuntu 14.04, the last time when I tried that, It seems that it is impossible to install it in Ubuntu 14.04 because python version is too low.

**Comment by cheoljoo** [comment]
thanks a lot.
